//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyWebSKF_GestionServicios.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRADORE
    {
        public int persona_id { get; set; }
        public string enmail { get; set; }
        public string sexo { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
