//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyWebSKF_GestionServicios.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdSKF_GestionServiciosEntities : DbContext
    {
        public BdSKF_GestionServiciosEntities()
            : base("name=BdSKF_GestionServiciosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<COMPRADORE> COMPRADORES { get; set; }
        public virtual DbSet<DETALLEPAQUETE> DETALLEPAQUETES { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<PAQUETE> PAQUETES { get; set; }
        public virtual DbSet<PERSONA> PERSONAS { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPODOCUMENTO> TIPODOCUMENTOS { get; set; }
        public virtual DbSet<TIPOSERVICIO> TIPOSERVICIOS { get; set; }
    }
}
