//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyWebSKF_GestionServicios.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEPAQUETE
    {
        public int id { get; set; }
        public int paquete_id { get; set; }
        public int servicio_id { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual PAQUETE PAQUETE { get; set; }
    }
}
