//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyWebSKF_GestionServicios.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int persona_id { get; set; }
        public int cargo_id { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaCese { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
