//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyWebSKF_GestionServicios.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int tipoDocumento_id { get; set; }
        public string numeroDocumento { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string celular { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
    
        public virtual COMPRADORE COMPRADORE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual TIPODOCUMENTO TIPODOCUMENTO { get; set; }
    }
}
